FROM node:17-alpine AS builder
WORKDIR /app
COPY ./package.json ./
RUN yarn
COPY . .
CMD ["yarn", "run", "build"]

FROM node:17-alpine
WORKDIR /app
COPY --from=builder /app ./
CMD [ "yarn" ,"run","start:dev-hmr"]